DROP DATABASE IF EXISTS top_songsDB;

CREATE DATABASE top_songsDB;

USE top_songsDB;

CREATE TABLE top5000 (
  id INT NOT NULL AUTO_INCREMENT,
  artist VARCHAR(45) NOT NULL,
  song VARCHAR(45) NOT NULL,
  year INTEGER(45) NOT NULL,
  data1 INTEGER(45) NOT NULL,
  data2 INTEGER(45) NOT NULL,
  data3 INTEGER(45) NOT NULL,
  data4 INTEGER(45) NOT NULL,
  data5 INTEGER(45) NOT NULL,
  PRIMARY KEY (id)
);
